In [19]:
import pandas as pd

In [3]:
paths = {
    'win10': '',
    'win11': r'C:\Users\Administrator\Downloads\Emissions_Totals_E_All_Data',
}

In [6]:
import platform

windows_version = platform.release()

if windows_version.startswith("10"):
    path = paths['win10']
elif windows_version.startswith("11"):
    path = paths['win11']

In [17]:
emissions_total     = 'Emissions_Totals_E_All_Data.csv'
emissions_noflag    = 'Emissions_Totals_E_All_Data_NOFLAG.csv'
flags               = 'Emissions_Totals_E_Flags.csv'
area_codes          = 'Emissions_Totals_E_AreaCodes.csv'

In [27]:
df_emissions_total = pd.read_csv(f'{path}\\{emissions_total}', encoding='latin-1')

In [28]:
df_emissions_total

,Area Code,Area Code (M49),Area,Item Code,Item,Element Code,Element,Source Code,Source,Unit,...,Y2020N,Y2021,Y2021F,Y2021N,Y2030,Y2030F,Y2030N,Y2050,Y2050F,Y2050N
0,2,'004,Afghanistan,5064,Crop Residues,7234,Direct emissions (N2O),3050,FAO TIER 1,kt,...,NaN,1.018600e+00,E,NaN,1.5337,F,NaN,1.9389,F,NaN
1,2,'004,Afghanistan,5064,Crop Residues,7236,Indirect emissions (N2O),3050,FAO TIER 1,kt,...,NaN,2.292000e-01,E,NaN,0.3451,F,NaN,0.4362,F,NaN
2,2,'004,Afghanistan,5064,Crop Residues,7230,Emissions (N2O),3050,FAO TIER 1,kt,...,NaN,1.247700e+00,E,NaN,1.8788,F,NaN,2.3751,F,NaN
3,2,'004,Afghanistan,5064,Crop Residues,724313,Emissions (CO2eq) from N2O (AR5),3050,FAO TIER 1,kt,...,NaN,3.306405e+02,E,NaN,497.8820,F,NaN,629.4015,F,NaN
4,2,'004,Afghanistan,5064,Crop Residues,723113,Emissions (CO2eq) (AR5),3050,FAO TIER 1,kt,...,NaN,3.306405e+02,E,NaN,497.8820,F,NaN,629.4015,F,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66503,5873,'198,OECD,6829,All sectors without LULUCF,7273,Emissions (CO2),3050,FAO TIER 1,kt,...,NaN,1.158563e+07,E,NaN,NaN,NaN,NaN,NaN,NaN,NaN
66504,5873,'198,OECD,6829,All sectors without LULUCF,717815,Emissions (CO2eq) from F-gases (AR5),3050,FAO TIER 1,kt,...,NaN,4.062662e+05,E,NaN,NaN,NaN,NaN,NaN,NaN,NaN
66505,5873,'198,OECD,6829,All sectors without LULUCF,724413,Emissions (CO2eq) from CH4 (AR5),3050,FAO TIER 1,kt,...,NaN,1.793427e+06,E,NaN,NaN,NaN,NaN,NaN,NaN,NaN
66506,5873,'198,OECD,6829,All sectors without LULUCF,724313,Emissions (CO2eq) from N2O (AR5),3050,FAO TIER 1,kt,...,NaN,7.831454e+05,E,NaN,NaN,NaN,NaN,NaN,NaN,NaN
66507,5873,'198,OECD,6829,All sectors without LULUCF,723113,Emissions (CO2eq) (AR5),3050,FAO TIER 1,kt,...,NaN,1.456847e+07,E,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [35]:
df_emissions_total_ch4 = df_emissions_total[df_emissions_total['Element'].str.contains('CH4')]
# df_emissions_total_ch4['Item'].unique()

In [36]:
df_emissions_total_ch4[df_emissions_total_ch4['Item'] == 'Manure Management']

,Area Code,Area Code (M49),Area,Item Code,Item,Element Code,Element,Source Code,Source,Unit,...,Y2020N,Y2021,Y2021F,Y2021N,Y2030,Y2030F,Y2030N,Y2050,Y2050F,Y2050N
24,2,'004,Afghanistan,5059,Manure Management,7225,Emissions (CH4),3050,FAO TIER 1,kt,...,NaN,24.1936,E,NaN,27.2114,F,NaN,35.2700,F,NaN
25,2,'004,Afghanistan,5059,Manure Management,7225,Emissions (CH4),3051,UNFCCC,kt,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,2,'004,Afghanistan,5059,Manure Management,724413,Emissions (CO2eq) from CH4 (AR5),3050,FAO TIER 1,kt,...,NaN,677.4208,E,NaN,761.9192,F,NaN,987.5600,F,NaN
30,2,'004,Afghanistan,5059,Manure Management,724413,Emissions (CO2eq) from CH4 (AR5),3051,UNFCCC,kt,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
269,3,'008,Albania,5059,Manure Management,7225,Emissions (CH4),3050,FAO TIER 1,kt,...,NaN,9.8473,E,NaN,14.2525,F,NaN,14.3347,F,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65990,5849,'908,Non-Annex I countries,5059,Manure Management,7225,Emissions (CH4),3051,UNFCCC,kt,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65995,5849,'908,Non-Annex I countries,5059,Manure Management,724413,Emissions (CO2eq) from CH4 (AR5),3050,FAO TIER 1,kt,...,NaN,155219.7472,E,NaN,161984.0936,F,NaN,184129.5512,F,NaN
65996,5849,'908,Non-Annex I countries,5059,Manure Management,724413,Emissions (CO2eq) from CH4 (AR5),3051,UNFCCC,kt,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
66282,5873,'198,OECD,5059,Manure Management,7225,Emissions (CH4),3050,FAO TIER 1,kt,...,NaN,4051.1005,E,NaN,4079.0315,F,NaN,4054.9125,F,NaN
66286,5873,'198,OECD,5059,Manure Management,724413,Emissions (CO2eq) from CH4 (AR5),3050,FAO TIER 1,kt,...,NaN,113430.8140,E,NaN,114212.8820,F,NaN,113537.5500,F,NaN

In [29]:
df_emmissions_noflag = pd.read_csv(f'{path}\\{emissions_noflag}', encoding='latin-1')
df_emmissions_noflag

,Area Code,Area Code (M49),Area,Item Code,Item,Element Code,Element,Source Code,Source,Unit,...,Y2014,Y2015,Y2016,Y2017,Y2018,Y2019,Y2020,Y2021,Y2030,Y2050
0,2,'004,Afghanistan,5064,Crop Residues,7234,Direct emissions (N2O),3050,FAO TIER 1,kt,...,1.458400e+00,1.242400e+00,1.194000e+00,1.061400e+00,8.986000e-01,1.217600e+00,1.317000e+00,1.018600e+00,1.5337,1.9389
1,2,'004,Afghanistan,5064,Crop Residues,7236,Indirect emissions (N2O),3050,FAO TIER 1,kt,...,3.281000e-01,2.795000e-01,2.687000e-01,2.388000e-01,2.022000e-01,2.740000e-01,2.963000e-01,2.292000e-01,0.3451,0.4362
2,2,'004,Afghanistan,5064,Crop Residues,7230,Emissions (N2O),3050,FAO TIER 1,kt,...,1.786500e+00,1.522000e+00,1.462700e+00,1.300300e+00,1.100800e+00,1.491600e+00,1.613300e+00,1.247700e+00,1.8788,2.3751
3,2,'004,Afghanistan,5064,Crop Residues,724313,Emissions (CO2eq) from N2O (AR5),3050,FAO TIER 1,kt,...,4.734225e+02,4.033300e+02,3.876155e+02,3.445795e+02,2.917120e+02,3.952740e+02,4.275245e+02,3.306405e+02,497.8820,629.4015
4,2,'004,Afghanistan,5064,Crop Residues,723113,Emissions (CO2eq) (AR5),3050,FAO TIER 1,kt,...,4.734225e+02,4.033300e+02,3.876155e+02,3.445795e+02,2.917120e+02,3.952740e+02,4.275245e+02,3.306405e+02,497.8820,629.4015
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66503,5873,'198,OECD,6829,All sectors without LULUCF,7273,Emissions (CO2),3050,FAO TIER 1,kt,...,1.261070e+07,1.252483e+07,1.240673e+07,1.245039e+07,1.254748e+07,1.217925e+07,1.096671e+07,1.158563e+07,NaN,NaN
66504,5873,'198,OECD,6829,All sectors without LULUCF,717815,Emissions (CO2eq) from F-gases (AR5),3050,FAO TIER 1,kt,...,3.890872e+05,3.819821e+05,3.849055e+05,3.929988e+05,3.971163e+05,3.947495e+05,3.987026e+05,4.062662e+05,NaN,NaN
66505,5873,'198,OECD,6829,All sectors without LULUCF,724413,Emissions (CO2eq) from CH4 (AR5),3050,FAO TIER 1,kt,...,1.937651e+06,1.925229e+06,1.882625e+06,1.916783e+06,1.938941e+06,1.952504e+06,1.824637e+06,1.793427e+06,NaN,NaN
66506,5873,'198,OECD,6829,All sectors without LULUCF,724313,Emissions (CO2eq) from N2O (AR5),3050,FAO TIER 1,kt,...,8.196996e+05,8.146365e+05,8.061011e+05,8.239154e+05,8.202014e+05,7.893120e+05,7.683432e+05,7.831454e+05,NaN,NaN
66507,5873,'198,OECD,6829,All sectors without LULUCF,723113,Emissions (CO2eq) (AR5),3050,FAO TIER 1,kt,...,1.575714e+07,1.564668e+07,1.548036e+07,1.558409e+07,1.570374e+07,1.531582e+07,1.395840e+07,1.456847e+07,NaN,NaN